"""Maintenance cleanup script to remove temporary artifacts and aged files."""
import os
import argparse
import time
from typing import List

WORKDIR = os.getcwd()
TARGETS_TEMP: List[str] = [
    os.path.join(WORKDIR, "page3162_layout.txt"),
    os.path.join(WORKDIR, "page3162_bbox.txt"),
    os.path.join(WORKDIR, "page3162_raw.txt"),
    os.path.join(WORKDIR, "page3162_ocr.txt"),
    os.path.join(WORKDIR, "analysis_report.md"),
]

# OCR PNGs generated by extractor use prefix 'ocr_page_'
PNG_PREFIX = "ocr_page_"


def remove_file(path: str, dry_run: bool) -> bool:
    """Remove a file if it exists.

    Returns True if removed (or would remove in dry-run), False otherwise.
    """
    if os.path.exists(path):
        if dry_run:
            print(f"DRY-RUN delete: {path}")
            return True
        try:
            os.remove(path)
            print(f"Deleted: {path}")
            return True
        except (OSError, PermissionError) as e:
            print(f"Failed to delete {path}: {e}")
    return False


def purge_temp(dry_run: bool) -> None:
    """Remove known temp artifacts and OCR PNGs in outputs directory."""
    for path in TARGETS_TEMP:
        remove_file(path, dry_run)
    # Remove OCR PNGs sprinkled in outputs directory
    outputs_dir = os.path.join(WORKDIR, "outputs")
    if os.path.isdir(outputs_dir):
        for name in os.listdir(outputs_dir):
            if name.startswith(PNG_PREFIX) and name.endswith(".png"):
                remove_file(os.path.join(outputs_dir, name), dry_run)


def purge_old_in_dir(dir_path: str, retention_days: int, dry_run: bool) -> None:
    """Delete files older than retention_days within dir_path."""
    if not os.path.isdir(dir_path):
        return
    now = time.time()
    cutoff = now - retention_days * 86400
    for name in os.listdir(dir_path):
        path = os.path.join(dir_path, name)
        try:
            st = os.stat(path)
        except OSError:
            continue
        if st.st_mtime < cutoff:
            remove_file(path, dry_run)


def main():
    """Parse arguments and perform cleanup tasks."""
    parser = argparse.ArgumentParser(
        description="Cleanup temp artifacts and old uploads/outputs"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be removed",
    )
    parser.add_argument(
        "--retention-days",
        type=int,
        default=14,
        help="Delete files older than N days in uploads/outputs",
    )
    args = parser.parse_args()

    print("Purging temp artifacts…")
    purge_temp(args.dry_run)
    print("Purging old uploads…")
    purge_old_in_dir(os.path.join(WORKDIR, "uploads"), args.retention_days, args.dry_run)
    print("Purging old outputs…")
    purge_old_in_dir(os.path.join(WORKDIR, "outputs"), args.retention_days, args.dry_run)


if __name__ == "__main__":
    main()
